### ISSUE TITLE
No support for Older version of android

### ISSUE THREAD

**Issue by AntarixCelusion** [weliem/blessed-kotlin#10]
Can you make minimum SDK support to 23 at least would be helpful @weliem

**Comment by weliem** [comment]
If you need support for Android 6, then I recommend trying the Java version of this library (blessed-android).

I think Android 6 is really old now, so I don't want to support that anymore. There were many issues with BLE at that time and I cleaned up the code of this library by removing all workarounds.

Sorry...

**Comment by AntarixCelusion** [comment]
Can we at least port to android 8 compatible if possible?
