### ISSUE TITLE
centralManager.scanForPeripherals()

### ISSUE THREAD

**Issue by SamBozman** [weliem/blessed-kotlin#13]
Hi, I am kind of new to BLE, but I was interested in trying your library. I did get the app/peripheral example working so I thought I would try scanning for any BLE signals within range. So to do this I changed your startScanning function:

`startScanning() {
        if(centralManager.isNotScanning) {
            centralManager.scanForPeripheralsWithServices(
                setOf(
                    BLP_SERVICE_UUID,
                    GLUCOSE_SERVICE_UUID,
                    HRS_SERVICE_UUID,
                    HTS_SERVICE_UUID,
                    PLX_SERVICE_UUID,
                    WSS_SERVICE_UUID
                )
            )
        }
    }`

to:

` fun startScanning() {
        if(centralManager.isNotScanning) {
            centralManager.scanForPeripherals()
        }
    }`

However, I do not get a list of BLE Peripherals, but instead just get the message, "Waiting for Measurement" as in the aforementioned example app. Can you explain how to see all BLE devices within range? Or do you have an example?

Thanks
Sam Bozman

**Comment by weliem** [comment]
The demo app shows received data, not found devices. So you have to make more modifications if you want to see found devices...
