### ISSUE TITLE
BluetoothCentralManagerCallback#onConnected not called for BluetootheCentralManager autoConnect methods

### ISSUE THREAD

**Issue by mobamipari** [weliem/blessed-kotlin#16]
Hi,

we are encountering an issue with the auto connect methods, specifically related to the `BluetoothCentralManagerCallback#onConnected` callback not being triggered as expected when a connection is being automatically established.

From our application logs, we observe the following entry:
BluetoothPeripheral - connected to 'BLEDevice' (BONDED) in 16.2 seconds
However, despite this successful connection message, the registered `BluetoothCentralManagerCallback` does not seem to be invoked.

Could you please help in investigating this issue? Additionally, if anyone else has experienced similar challenges, we would appreciate any insights or suggestions.

Thank you for your assistance.

**Comment by weliem** [comment]
Please share a log so I can see what is happening
