### ISSUE TITLE
Adding Blessed3 Library into a project

### ISSUE THREAD

**Issue by SamBozman** [weliem/blessed-kotlin#17]
Hi,
When trying to add your library repository and dependencies I was getting funny errors. After some google research I found on StackOverflow this information:

_Support for Kotlin Gradle scripts is fairly new in Android — for example, Android Studio only added support for it in version 4.0. Most of the instructions that you will see online will be for Groovy Gradle scripts, and you will need to make some minor conversions.
In this case, this Groovy:_
**maven { url "https://jitpack.io" }**
...turns into this Kotlin:
**maven { url = uri("https://jitpack.io") }**

So, I added this to the Settings Gradle:
`dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}`

This change worked but the dependencies did not. 
When I add :
`dependencies {
    implementation "com.github.weliem:blessed-kotlin:3.0.7"
    implementation 'com.jakewharton.timber:timber:5.0.1'
}`

I get many errors, the main one being 
**"Unexpected tokens (use ';' to separate expressions on the same line)"**
This was the same error I originally got with the 'maven url' problem.
But also this error:
 **Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun Project.dependencies(configuration: DependencyHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl**

Any ideas?
Thanks
Sam Bozman

**Comment by randalln** [comment]
This doc could be useful: https://developer.android.com/build/migrate-to-kotlin-dsl

I'm using the Kotlin DSL in [my app](https://github.com/randalln/fitbit-heart-rate-service/tree/main/Android) if you want to see a working example, but here are the bits you probably need:

settings.gradle.kts
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        ...
        maven { setUrl("https://jitpack.io") }
    }
}
```

app/build.gradle.kts
```
dependencies {
    implementation("com.github.weliem:blessed-kotlin:3.0.7")
    implementation("com.jakewharton.timber:timber:5.0.1")
}
```
