### ISSUE TITLE
I don't seem to get the logs in logcat from the library

### ISSUE THREAD

**Issue by pAlkesz** [weliem/blessed-kotlin#4]
Hi!

This might be a stupid question but even though I call enableLogging on the centralBluetoothManager object that I have, I do not see any of the logs appearing in logcat when I am trying to filter to the package name or any of the tags that I can see in the source code. I want to get some logs about what is happening exactly during connection with a probably faulty BLE device I have. Is there any other stuff that I have to do in order to get the logs from the library?

Thanks for the answer in advance and sorry if I just missed some simple AS setting or something like that.

**Comment by weliem** [comment]
This library uses Timber for logging. So make sure you add it as a dependency:
`implementation 'com.jakewharton.timber:timber:5.0.1'`

Then you need to initialize it when your app starts up:
`Timber.plant(Timber.DebugTree())`

**Comment by pAlkesz** [comment]
Yes that solved it, thanks for the information. I am closing the issue since it's solved. Many thanks for the library, it saved me a lot of headache :)
