### ISSUE TITLE
Writing to a certain characteristic of a connected device from a function, on button click or on variable change. 

### ISSUE THREAD

**Issue by thirstyone** [weliem/blessed-kotlin#5]
Probably, I am too stupid, but could you please provide an example of writing to a characteristic not from a callback, but at a random time. In my app I connect to my device, and once connected, I should be able to write to a characteristic. The thing is, to do so, I need to have a peripheral object, which is sort of available only in the callback. 

So far, I created a `private lateinit var myPeripheral: BluetoothPeripheral`, and assign it like that: 
```
override fun onServicesDiscovered(peripheral: BluetoothPeripheral) {
            myPeripheral = peripheral
```
and then I can do `    myPeripheral.writeCharacteristic`
but I am not sure at all if this is a valid workaround.

**Comment by weliem** [comment]
Sure, that's one way of solving it.

You could also ask the BluetoothCentralManager for your peripheral:
`centralManager.getConnectedPeripherals()
`
