### ISSUE TITLE
Data Loss Reading Characteristic

### ISSUE THREAD

**Issue by wsghazi** [weliem/blessed-kotlin#6]
In our project we are trying to read JSON data from the peripheral but is getting cutoff after 600 bytes. Our L2CAP MTU max is 247 bytes on the peripheral. The peripheral handles the chunking of the data when it sends it to the phone. So we issue several `peripheral.readCharacterisitic()` on the same characteristic until we receive an "EOM" String.

The problem occurs on the first read of the Data, we could expect the data being sent to be in multiples of 247 bytes, but the first chunk cuts off at 600 bytes. 

When we receive the second chunk of Data on the subsequent `peripheral.readCharacterisitic()` call, we receive the tail end of the Data. Between the first chunk and second chunk, there is a lot of missing Data. 

We are not receiving any Bluetooth Errors that would indicate there is an issue, and we know that we can receive the Data because we tested with an iOS project on the same peripheral device. The iOS App is able to connect and receive the complete Data packets and is able to parse the Data into JSON without any problems.  

We noticed the Data loss because parsing it was throwing an error. 

Is there anything we can do to trouble shoot this problem? Any tips or tricks, are very welcome.

Thank You

**Comment by weliem** [comment]
According to the BLE standard the maximum length of a characteristic value is 512 bytes. So the behaviour you are seeing is correct.

**Comment by weliem** [comment]
It is better to send large data via notifications rather than using a long read

**Comment by wsghazi** [comment]
Thank you @weliem, appreciate the feedback.
