### ISSUE TITLE
Callback for disconnected in BluetoothPeripheral

### ISSUE THREAD

**Issue by gelhan** [weliem/blessed-kotlin#7]
Hi! First of all, thank you for your work and this super organized library :) question: is it possible to get a "disconnected" callback for the BluetoothPeripheral itself when e.g. I turn off my Bluetooth device? I only seem to get a callback for the CentralManager but not for the Peripheral itself.

**Comment by weliem** [comment]
The concept is that scanning, connecting and disconnecting is managed by the CentralManager. 

If you want to receive a disconnect on your peripheral you can simply add an extension function to your peripheral and call it from the central manager when you get the disconnect.

**Comment by gelhan** [comment]
Thank you, will do!
