### ISSUE TITLE
How to set buffer size in blood pressure monitor

### ISSUE THREAD

**Issue by vivek-modi** [weliem/blessed-kotlin#8]
Hello, thanks for great library providing. I want to know how can I set buffer size of blood pressure monitor? The problem is that when I have taken reading from monitor without connecting to device. It store that value in the memory. When I connect the monitor to device it gives me all reading value + new reading value. Is there way we can fix this issue?

**Comment by weliem** [comment]
What you are describing is a device specific issue. Please consult the manufacturer of the device to see if there is a way to change that behavior....
